import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function fixUserDuplicatePackage() {
  const targetDigits = '604023517';

  console.log(`Searching for user matching phone/username ending with ${targetDigits}...`);

  const users = await prisma.users.findMany({
    where: {
      OR: [
        { phone: { contains: targetDigits } },
        { username: { contains: targetDigits } }
      ]
    }
  });

  if (users.length === 0) {
    console.error(`ERROR: No user found matching phone ${targetDigits}`);
    process.exit(1);
  }

  for (const user of users) {
    console.log(`\n==================================================`);
    console.log(`PROCESSING USER: ${user.full_name} (${user.phone}) | ID: ${user.id}`);
    console.log(`Current Balance: ${user.balance} | Current Withdrawable: ${user.withdrawable_balance}`);
    console.log(`==================================================`);

    // Fetch user investments
    const investments = await prisma.investments.findMany({
      where: { user_id: user.id },
      include: { plan: true },
      orderBy: { created_at: 'asc' }
    });

    console.log(`Total investments found: ${investments.length}`);
    investments.forEach((inv, index) => {
      console.log(` [${index + 1}] ID: ${inv.id} | Plan: ${inv.plan?.name} | Amount: ${inv.amount} | Daily Profit: ${inv.daily_profit} | Status: ${inv.status} | Created: ${inv.created_at}`);
    });

    if (investments.length <= 1) {
      console.log(`User only has ${investments.length} investment. No duplicate investment to remove.`);
    } else {
      // Keep the first investment (legitimate), remove/cancel subsequent duplicates
      const legitInv = investments[0];
      const duplicateInvs = investments.slice(1);

      console.log(`\n--> Keeping Legitimate Investment: ID ${legitInv.id} (${legitInv.plan?.name}, R${legitInv.amount})`);

      for (const dupInv of duplicateInvs) {
        console.log(`\n--> Cleaning up Duplicate Investment: ID ${dupInv.id} (${dupInv.plan?.name}, R${dupInv.amount})`);

        // Find all profit earnings generated by this duplicate investment
        const dupProfits = await prisma.investment_profits.findMany({
          where: { investment_id: dupInv.id }
        });

        const totalExcessProfit = dupProfits.reduce((sum, p) => sum + parseFloat(p.amount || 0), 0);
        console.log(`   Excess profits earned from duplicate package: R${totalExcessProfit.toFixed(2)} (${dupProfits.length} payout(s))`);

        // Reverse referral commissions earned by uplines from this duplicate package's payouts
        const dupReferralComms = await prisma.referral_commissions.findMany({
          where: { from_user_id: user.id, description: { contains: dupInv.plan?.name || 'daily profit' } }
        });

        for (const refComm of dupReferralComms) {
          const commAmount = parseFloat(refComm.amount || 0);
          console.log(`   Reversing referral commission of R${commAmount} for upline ${refComm.user_id}`);

          const referrer = await prisma.users.findUnique({ where: { id: refComm.user_id } });
          if (referrer) {
            const newRefBal = Math.max(0, parseFloat(referrer.withdrawable_balance || 0) - commAmount);
            await prisma.users.update({
              where: { id: refComm.user_id },
              data: { withdrawable_balance: newRefBal }
            });
          }

          await prisma.referral_commissions.delete({ where: { id: refComm.id } }).catch(() => {});
        }

        // Delete investment profits for duplicate package
        if (dupProfits.length > 0) {
          await prisma.investment_profits.deleteMany({
            where: { investment_id: dupInv.id }
          });
          console.log(`   Deleted ${dupProfits.length} duplicate investment_profits records.`);
        }

        // Delete transactions linked to duplicate package
        const deletedTxs = await prisma.transactions.deleteMany({
          where: {
            user_id: user.id,
            OR: [
              { reference_id: dupInv.id },
              { description: { contains: dupInv.id } }
            ]
          }
        });
        console.log(`   Deleted ${deletedTxs.count} transaction records linked to duplicate investment.`);

        // Delete or mark duplicate investment as CANCELLED
        await prisma.investments.delete({
          where: { id: dupInv.id }
        });
        console.log(`   Deleted duplicate investment record ID ${dupInv.id}`);

        // Deduct excess profits from user's withdrawable balance
        const currentUser = await prisma.users.findUnique({ where: { id: user.id } });
        const oldWithdrawable = parseFloat(currentUser.withdrawable_balance || 0);
        const newWithdrawable = Math.max(0, oldWithdrawable - totalExcessProfit);

        await prisma.users.update({
          where: { id: user.id },
          data: { withdrawable_balance: newWithdrawable }
        });

        console.log(`   Adjusted user withdrawable_balance from R${oldWithdrawable.toFixed(2)} to R${newWithdrawable.toFixed(2)} (-R${totalExcessProfit.toFixed(2)})`);
      }
    }

    // Check deposits for duplicates
    const deposits = await prisma.deposits.findMany({
      where: { user_id: user.id },
      orderBy: { created_at: 'asc' }
    });

    console.log(`\nTotal deposits found: ${deposits.length}`);
    deposits.forEach((dep, i) => {
      console.log(` [${i + 1}] ID: ${dep.id} | Amount: ${dep.amount} | Status: ${dep.status} | Track/Ref: ${dep.track_id || dep.tx_hash || 'N/A'} | Created: ${dep.created_at}`);
    });

    if (deposits.length > 1) {
      const approvedDeposits = deposits.filter(d => d.status === 'APPROVED');
      if (approvedDeposits.length > 1) {
        console.log(`\n--> Normalizing Deposits: Found ${approvedDeposits.length} approved deposits.`);
        // Keep first approved deposit, mark others as CANCELLED_DUPLICATE
        for (let i = 1; i < approvedDeposits.length; i++) {
          const dupDep = approvedDeposits[i];
          await prisma.deposits.update({
            where: { id: dupDep.id },
            data: { status: 'CANCELLED_DUPLICATE' }
          });
          console.log(`   Updated duplicate deposit ID ${dupDep.id} (R${dupDep.amount}) status to CANCELLED_DUPLICATE`);
        }
      }
    }

    // Final balance recalculation & safety check
    const finalUser = await prisma.users.findUnique({ where: { id: user.id } });
    console.log(`\n================ FINAL USER STATE ================`);
    console.log(`Name: ${finalUser.full_name}`);
    console.log(`Phone: ${finalUser.phone}`);
    console.log(`Balance: R${parseFloat(finalUser.balance || 0).toFixed(2)}`);
    console.log(`Withdrawable Balance: R${parseFloat(finalUser.withdrawable_balance || 0).toFixed(2)}`);

    const finalInvs = await prisma.investments.findMany({
      where: { user_id: user.id, status: 'ACTIVE' },
      include: { plan: true }
    });
    console.log(`Active Investments remaining: ${finalInvs.length}`);
    finalInvs.forEach(inv => console.log(` - ${inv.plan?.name} (R${inv.amount})`));
    console.log(`==================================================\n`);
  }

  await prisma.$disconnect();
}

fixUserDuplicatePackage().catch(err => {
  console.error('Error running fix:', err);
  process.exit(1);
});
